### ISSUE TITLE
Getting error for Brazil Number

### ISSUE THREAD

**Issue by aekanshpartani** [brick/phonenumber#13]
Array
(
    [error] => No valid contact for +5575*******
   
)

I got this error when I tried searching this number. On some online searched I found that it's from Brazil but it's giving error here.

**Comment by aekanshpartani** [comment]
if (!$number->isValidNumber()) {
            return ['error' => 'No valid contact for ' . $phone];
        }
        
        I think this is returning false here.

**Comment by BenMorel** [comment]
Hi, can you please give a complete reproduce code? It's unclear what the problem is here.

**Comment by aekanshpartani** [comment]
So basically I am using this to get country code for numbers registered.
We received a brazil number.

`      $number = PhoneNumber::parse($phone);
        if (!$number->isValidNumber()) {
            return ['error' => 'No valid contact for ' . $phone];
        }
        return $number->getRegionCode();
`
I am checking if number is valid first and return error if not and return region code if valid. But for that number I got error even when the number was perfectly correct as  it was used on whatsapp

**Comment by BenMorel** [comment]
Hi, without the number in question, I won't be able to help. You can email it to me if you do not want to make it public!

**Comment by BenMorel** [comment]
Closing due to lack of feedback.
