### ISSUE TITLE
Netherlands Antilles Country Code: Missing or invalid default region

### ISSUE THREAD

**Issue by masonmcelvain** [brick/phonenumber#14]
Hello!

When trying to parse phone numbers of the format `599 XXXX XXXX` with country code `AN`, `parse()` raises a `PhoneNumberParseException` with the message `Missing or invalid default region.`.

e.g.
```php
try {
   $number = PhoneNumber::parse('59912345678', 'AN');
   echo $number->format(PhoneNumberFormat::E164);
} catch (PhoneNumberParseException $e) {
   echo $e->getMessage();
}
```

[Netherlands Antilles was dissolved in 2010](https://en.wikipedia.org/wiki/Telephone_numbers_in_Cura%C3%A7ao_and_the_Caribbean_Netherlands#:~:text=International%20Call%20Prefix%3A%2000,%2C%20Sint%20Eustatius%20and%20Saba) - is this why phone numbers from this country are not supported by `parse()`?

The [Netherlands Antilles Alpha-2 code was 'AN'](https://www.iso.org/obp/ui/#iso:code:3166:AN), and the Alpha-2 codes of most other countries seem to work with `parse()`.

The [country calling code of Netherlands Antilles](https://countrycode.org/netherlandsantilles) was `599`, and it is now in use in Curaçao and the Caribbean Netherlands.

My company has a lot of legacy customers whose phone numbers begin with `599` and whose country codes are `AN`. It would really help us out if `AN` was supported by `parse()`.

Thanks for your time and maintaining this package 😄

**Comment by masonmcelvain** [comment]
While we're on this subject, I've identified several country iso codes that are completely unrecognized by `parse()` as well
`Country calling code supplied was not recognised` is the error message from the `PhoneNumberParseException`.

* `PF` - [French Polynesia](https://www.iso.org/obp/ui/#iso:code:3166:PF)
* `CY` - [The Republic of Cypress](https://www.iso.org/obp/ui/#iso:code:3166:CY)
* `KR` - [Republic of Korea (South Korea)](https://www.iso.org/obp/ui/#iso:code:3166:KR)
*

**Comment by BenMorel** [comment]
Hi, this library is a wrapper for [libphonenumber-for-php](https://github.com/giggsey/libphonenumber-for-php), so I think this issue should be reported there as they should know more about this!
