### ISSUE TITLE
Any plans to add geolocation?

### ISSUE THREAD

**Issue by nfn** [brick/phonenumber#15]
Hi

I would like to use brick phoneumber, but it's missing geolocation features.
Are there any plans to add this in future releases?

Thanks

**Comment by BenMorel** [comment]
Hi, what do you mean by geolocation?

**Comment by nfn** [comment]
Hi

I was talking about  PhoneNumberOfflineGeocoder

https://github.com/giggsey/libphonenumber-for-php/blob/master/docs/PhoneNumberOfflineGeocoder.md

**Comment by nfn** [comment]
Closed this by mistake, sorry

**Comment by BenMorel** [comment]
Implemented in [0.4.0](https://github.com/brick/phonenumber/releases/tag/0.4.0)! Use `PhoneNumber::getDescription()`.
