### ISSUE TITLE
Can't catch exception

### ISSUE THREAD

**Issue by DannyRidgway** [brick/phonenumber#5]
Hi, 

I'm having trouble catching the exceptions using the following code.

```
try {
      $numberParsed = PhoneNumber::parse('+333', $region);
      $numberValid = PhoneNumber::parse('+333', $region)->isValidNumber();
		    
}catch (PhoneNumberParseException $e) {
      // 'The string supplied is too short to be a phone number.'
      error_log($e);
}

```
Throws the error 

```
PHP Fatal error:  Uncaught libphonenumber\NumberParseException: The string supplied is too short to be a phone number. in /www/zendsvr6/htdocs/ridgwad/stream_dev_1/core/utils/composer/vendor/giggsey/libphonenumber-for-php/src/PhoneNumberUtil.php:1650
Stack trace:
#0 /www/zendsvr6/htdocs/ridgwad/stream_dev_1/core/utils/composer/vendor/giggsey/libphonenumber-for-php/src/PhoneNumberUtil.php(3023): libphonenumber\PhoneNumberUtil->parseHelper('+333', 'GB', false, true, Object(libphonenumber\PhoneNumber))
```

Any ideas what I'm doing wrong?

**Comment by BenMorel** [comment]
Hi, I can see that you closed your issue without any explanation, did you find the solution yourself?

I just ran your code above, and I do get a `Brick\PhoneNumber\PhoneNumberParseException`, that wraps the `libphonenumber\NumberParseException`, as expected.

You're not supposed to get an "Uncaught libphonenumber\NumberParseException" error, so I'm a bit surprised by the error message.
