### ISSUE TITLE
getRegionCode is not defined

### ISSUE THREAD

**Issue by akimkelar** [brick/phonenumber#7]
getRegionCode, mentioned on the main page, is not defined in libphonenumber\PhoneNumber

**Comment by BenMorel** [comment]
Hi, this library is a wrapper around libphonenumber.

The methods documented in the README of this library are for `Brick\PhoneNumber\PhoneNumber`, not `libphonenumber\PhoneNumber`.

As you can see in the [source code](https://github.com/brick/phonenumber/blob/b7d11be8a47f8493e82866fbb9cd8a110ebbcbe7/src/PhoneNumber.php#L106-L115), `Brick\PhoneNumber\PhoneNumber::getRegionCode()` internally wraps `libphonenumber\PhoneNumberUtil::getRegionCodeForNumber()`.

I'm closing this issue, please feel free to comment if I misunderstood your request.
